// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaE8xYzXbYyAtPmIBDjgBXUOXcObQmdeA',
    appId: '1:242681723827:web:2ae6d21e089eae3a4669c6',
    messagingSenderId: '242681723827',
    projectId: 't-tasks-manager',
    authDomain: 't-tasks-manager.firebaseapp.com',
    storageBucket: 't-tasks-manager.appspot.com',
    measurementId: 'G-QMGZFY3D0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbRNcw2FVQnLJCgdhkrX8oT43lpcNm8dk',
    appId: '1:242681723827:android:8021f0af58b3add14669c6',
    messagingSenderId: '242681723827',
    projectId: 't-tasks-manager',
    storageBucket: 't-tasks-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAws4Lyl1J0y82AAeIp2nkEZ9KpEmPZN8',
    appId: '1:242681723827:ios:8b996703901c11ad4669c6',
    messagingSenderId: '242681723827',
    projectId: 't-tasks-manager',
    storageBucket: 't-tasks-manager.appspot.com',
    iosBundleId: 'com.example.tTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAws4Lyl1J0y82AAeIp2nkEZ9KpEmPZN8',
    appId: '1:242681723827:ios:7d80bd6dc79106064669c6',
    messagingSenderId: '242681723827',
    projectId: 't-tasks-manager',
    storageBucket: 't-tasks-manager.appspot.com',
    iosBundleId: 'com.example.tTaskManager.RunnerTests',
  );
}
