name: Flutter CI CD
on:
  push:
    branches:
      - 'main'
      - 'dev-tanvir'

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.getVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: set up Java 12
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.6'

      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter build apk --release

      - name : Upload APK file
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/flutter-apk
    
      - name: Get apk info
        id: apk-info
        uses: hkusu/apk-info-action@v1
        with:
          apk-path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

  